address https://github.com/facebook/libphenom/issues/7
Use a good old fashioned #define instead of an inline to
avoid this compiler bug:

```
corelib/variant/json-dump.c: In function ‘dump_string’:
corelib/variant/json-dump.c:34: error: inlining failed in call to ‘dump’: call is unlikely and code size would grow
corelib/variant/json-dump.c:151: error: called from here
make: *** [corelib/variant/libphenom_a-json-dump.o] Error 1
```