Fixup travis build for CK upgrade
Bump the CK version that we pull in for travis builds.

Can't use unlikely in this code branch, because the code branch is already
unlikely and the code size would grow:

```
thirdparty/ck/include/ck_ring.h:243:1: error: inlining failed in call to 'ck_ring_enqueue_spmc': call is unlikely and code size would grow [-Werror=inline]
corelib/job.c:539:12: error: called from here [-Werror=inline]
```